// nextjs/src/app/chats/[id]/page.tsx
import { getChat, loadUser } from "@/lib"
import { FormEvent, useState } from "react"

'use client'

enum Status {
	Empty,
	Editing,
	Submitting
}

function Messages({ initial }: { initial: string[] }) {

	const [submitted, setSubmitted] = useState<string[]>([])
	const [edited, setEdited] = useState('')
	const [status, setStatus] = useState(Status.Empty)

	async function handleSubmit(e: FormEvent) {

	}

	async function handleMessageChange(e: FormEvent) {

	}

	const messages = [...initial, ...submitted]

	return (
		<>
			{messages.map(message => <p>{message}</p>)}

			<form method="POST" onSubmit={handleSubmit}>
				<input name="message" type="text" autoFocus value={edited} onChange={handleMessageChange} />
				<button disabled={status === Status.Submitting}>Send</button>
			</form>
		</>
	)
}

export default async function Chat({ id }: { id: number }) {
	const [friend, chat] = await Promise.all([(loadUser(id)), (getChat(id))])

	return (
		<main>
			<h1>Chat with {friend.first_name}</h1>

			<Messages initial={chat} />
		</main>
	)
}

// svelte/src/routes/chats/[id]/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms'
	import type { SubmitEvent } from '$lib'
	import { FormEnhancer } from '$lib'

	export let data

	let messageForm: HTMLFormElement

	let submittedMessages: string[] = []

	const formEnhancer = new FormEnhancer(() => messageForm, { submit: appendMessage })

	const sending = formEnhancer.submitting

	function appendMessage(event: SubmitEvent) {
		const value = event.formData.get('message')
		const message = typeof value === 'string' ? value : ''
		submittedMessages = [...submittedMessages, message]
	}
</script>

<h1>Chat with {data.friend.first_name}</h1>

{#await data.messages}
	<span>Loading...</span>
{:then messages}
	{#each messages.concat(submittedMessages) as message}
		<p>{message}</p>
	{/each}
{/await}

<form bind:this={messageForm} method="POST" use:enhance={(e) => formEnhancer.submit(e)}>
	<!-- svelte-ignore a11y-autofocus -->
	<input name="message" type="text" autofocus />
	<button disabled={$sending}>Send</button>
</form>
